# Generated by Django 3.2.4 on 2021-06-16 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_prestamomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamomodel',
            options={'ordering': ['-prestamoFechaInicio'], 'verbose_name': 'prestamo', 'verbose_name_plural': 'prestamos'},
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='prestamoFechaInicio',
            field=models.DateField(db_column='fecha_inicio', default=datetime.datetime(2021, 6, 15, 21, 0, 7, 996183), verbose_name='Fecha de inicio del prestamo'),
        ),
        migrations.AlterModelTable(
            name='prestamomodel',
            table='prestamos',
        ),
    ]
