# Generated by Django 3.2.4 on 2021-06-16 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20210615_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libromodel',
            options={'ordering': ['-libroEdicion', '-libroCantidad', 'libroNombre'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.AlterField(
            model_name='libromodel',
            name='libroAutor',
            field=models.TextField(db_column='autor', help_text='Ingrese el autor', verbose_name='Auto del libro'),
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='libro',
            field=models.ForeignKey(db_column='libro_id', help_text='Seleccione el libro a prestar', on_delete=django.db.models.deletion.PROTECT, related_name='libroPrestamos', to='gestion.libromodel', verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='prestamoFechaInicio',
            field=models.DateField(db_column='fecha_inicio', default=django.utils.timezone.now, verbose_name='Fecha de inicio del prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', help_text='Seleccione el usuario a prestar', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPrestamos', to='gestion.usuariomodel', verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='libromodel',
            unique_together={('libroNombre', 'libroEdicion', 'libroAutor')},
        ),
        migrations.AlterModelTable(
            name='libromodel',
            table='libros',
        ),
    ]
