# Generated by Django 3.2.4 on 2021-06-17 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20210615_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libromodel',
            name='deleteAt',
            field=models.DateTimeField(db_column='delete_at', null=True),
        ),
        migrations.AddField(
            model_name='libromodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='update_at'),
        ),
    ]
