# Generated by Django 3.2.4 on 2021-06-22 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20210617_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libromodel',
            name='deleteAt',
        ),
        migrations.AddField(
            model_name='libromodel',
            name='deletedAt',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='libromodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='prestamoFechaInicio',
            field=models.DateField(db_column='fecha_inicio', default=datetime.date.today, verbose_name='Fecha de inicio del prestamo'),
        ),
    ]
