# Generated by Django 3.2.4 on 2021-06-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_agregue_relate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioCorreo',
            field=models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='Correo del usuario'),
        ),
    ]
