# Generated by Django 3.2.4 on 2021-06-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_agregue_relate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioTelefono',
            field=models.CharField(db_column='telefono', max_length=10),
        ),
    ]
